name: e_obra_ph
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  go_router: ^15.2.0
  flutter_rating_bar: ^4.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  http: ^1.4.0
  crypto: ^3.0.6
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
